### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by pzel**

### CODE REVIEW

**Comment by studzien** [comment]
Would it make sense to create a matrix of these 2 configurations, so that they appear as separate "jobs" in Travis?

**Comment by pzel** [comment]
Yes, but maybe after we merge ets-tracker?
1. merge this to get going
2. merge ets tracker
3. adapt travis yml to use N matrices

**Comment by studzien** [comment]
Hmm, I already merged `ets-tracker`. Is this an incorrect order?

**Comment by pzel** [comment]
@studzien I'm off to bed. Feel free to rebase this, add the matrix thingie, and merge :)

**Pull request merged**
